-- Course Table
--First Year First Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ENG 1', 'INTRODUCTION TO COLLEGE ENGLISH', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 101', 'COLLEGE ALGEBRA', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('CHEM 111', 'GENERAL CHEMISTRY I', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('CHEM 111L', 'GENERAL CHEMISTRY I (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHIST', 'PHILIPPINE HISTORY', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('DRAW 111', 'ENGINEERING DRAWING I', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('GE 101', 'ENGINEERING ORIENTATION', 1 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 205', 'PLANE AND SPHERICAL TRIGONOMETRY', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('THY 1', 'CONTEXTUALIZED SALVATION HISTORY', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PE 1', 'PHYSICAL EDUCATION 1', 2, 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ENG 1', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 101', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('CHEM 111', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('CHEM 111L', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHIST', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('DRAW 111', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('GE 101', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 205', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('THY 1', 'First Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PE 1', 'First Semester', 'First Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--First Year Second Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ENG 2', 'READING & THINKING SKILLS FOR ACADEMIC STUDY',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 104', 'ANALYTIC GEOMETRY', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 215', 'SOLID MENSURATION', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('RC', 'RIZAL COURSE',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('LIT 101A', 'WORLD LITERATURES',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 201', 'ADVANCED ALGEBRA',  2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('THY 2', 'CHURCH AND SACRAMENTS',  2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PE 2', 'PHYSICAL EDUCATION 2',2 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ENG 2', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 104', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 215', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('RC', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('LIT 101A', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 201', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('THY 2', 'Second Semester', 'First Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PE 2', 'Second Semester', 'First Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Second Year First Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('FIL 1', 'KOMUNIKASYON SA AKADEMIKONG FILIPINO', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ENG 3', 'ACADEMIC WRITING SKILLS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 108', 'DIFFERENTIAL CALCULUS',  4 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHYS 202', 'COLLEGE PHYSICS I',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHYS 202L', 'COLLEGE PHYSICS I (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('LIT 102A', 'PHILIPPINE LITERATURES',  3 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 201', ' COMPUTER PROGRAMMING I',  0, 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHL 5', 'CHRISTIAN ETHICS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PE 3', 'PHYSICAL EDUCATION 3', 2 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('FIL 1', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ENG 3', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 108', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHYS 202', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHYS 202L', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('LIT 102A', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 201', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHL 5', 'First Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PE 3', 'First Semester', 'Second Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Second Year Second Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('FIL 2', 'PAGBASA AT PAGSULAT TUNGO SA PANANALIKSIK', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 109', 'INTEGRAL CALCULUS', 4 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHYS 205', 'COLLEGE PHYSICS II',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHYS 205L', 'COLLEGE PHYSICS II (LAB)',  0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PGC', 'PHIL GOVERNMENT AND CONSTITUTION', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PHL 2/102', 'LOGIC',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PSY 1', ' GENERAL PSYCHOLOGY',  3, 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 202', 'COMPUTER PROGRAMMING II', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('PE 4', 'PHYSICAL EDUCATION 4', 2 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('FIL 2', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 109', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHYS 205', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHYS 205L', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PGC', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PHL 2/102', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PSY 1', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 202', 'Second Semester', 'Second Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('PE 4', 'Second Semester', 'Second Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Third Year First Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 311', 'DISCRETE MATHEMATICS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 312', 'TECHNICAL COMPUTING', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 313', 'VECTOR ANALYSIS',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MECH 311', 'STATICS OF RIGID BODIES',  3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ETAR', 'ECONOMICS W/ TAXATION AND AGRARIAN REFORM', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('CNET 311', 'COMPUTER NETWORKS I',  0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('EE 306A', ' CIRCUIT ANALYSIS I',  3, 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 311', 'ELECTRONIC DEVICES AND CIRCUITS' , 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 311L', 'ELECTRONIC DEVICES AND CIRCUITS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 208', 'DIFFERENTIAL EQUATIONS', 3 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 311', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 312', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 313', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ETAR', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MECH 311', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('CNET 311', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('EE 306A', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 311', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 311L', 'First Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 208', 'First Semester', 'Third Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Third Year Second Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 321', 'ADVANCED ENGINEERING MATHEMATICS FOR ECE', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MATH 301', 'PROBABILITY THEORY AND RANDOM PROCESSES', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 321', 'COMPUTER AIDED CIRCUIT DESIGN & SIMULATION', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MECH 312', 'DYNAMICS OF RIGID BODIES', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('EE 306B', 'CIRCUIT ANALYSIS II', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('CNET 321', 'COMPUTER NETWORKS II', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('EE 306BL', 'CIRCUIT ANALYSIS II (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 321', 'ELECTRONIC CIRCUIT ANALYSIS AND DESIGN', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 321L', 'ELECTRONIC CIRCUIT ANALYSIS AND DESIGN (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 322', 'MATERIAL SCIENCE ENGINEERING', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 323', 'ELECTROMAGNETICS', 3 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 321', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MATH 301', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 321', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MECH 312', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('EE 306B', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('CNET 321', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('EE 306BL', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 321', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 321L', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 322', 'Second Semester', 'Third Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 323', 'Second Semester', 'Third Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Fourth Year First Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 411', 'LOGIC CIRCUITS & SWITCHING THEORY', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 411L', 'LOGIC CIRCUITS & SWITCHING THEORY (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('MECH 313', 'MECHANICS OF DEFORMABLE BODIES', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ENE 300', 'ENVIRONMENTAL ENGINEERING', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ME 302', 'BASIC THERMODYNAMICS', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('EE 307', 'ENERGY CONVERSION', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('EE 307L', 'ENERGY CONVERSION (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 411', 'SIGNALS, SPECTRA & SIGNAL PROCESSING', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 411L', 'SIGNALS, SPECTRA & SIGNAL PROCESSING (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 412', 'PRINCIPLES OF COMMUNICATIONS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 412L', 'PRINCIPLES OF COMMUNICATIONS (LAB)', 0 , 1)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 411', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 411L', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('MECH 313', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ENE 300', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ME 302', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('EE 307', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('EE 307L', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 411', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 411L', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 412', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 412L', 'First Semester', 'Fourth Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Fourth Year Second Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 421', 'NUMERICAL METHODS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MATH 421L', 'NUMERICAL METHODS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 421', 'MICROPROCESSOR SYSTEMS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 421L', 'MICROPROCESSOR SYSTEMS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('GE 301', 'ENGINEERING ECONOMY', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 421', 'INDUSTRIAL ELECTRONICS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 421L', 'INDUSTRIAL ELECTRONICS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 422', 'DIGITAL COMMUNICATIONS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 422L', 'DIGITAL COMMUNICATIONS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-MR', 'METHODS OF RESEARCH', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-ELEC1', 'ADVANCED ELECTRONICS', 3 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 421', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MATH 421L', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 421', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 421L', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('GE 301', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 421', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 421L', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 422', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 422L', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-MR', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-ELEC1', 'Second Semester', 'Fourth Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Fifth Year First Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 512', 'EMBEDDED SYSTEMS AND AUTOMATION', 0 , 2)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('COMP 511', 'COMPUTER SYSTEMS ARCHITECTURE', 2 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('GE 302', 'ENGINEERING MANAGEMENT', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 511', 'FEEDBACK AND CONTROL SYSTEMS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 511L', 'FEEDBACK AND CONTROL SYSTEMS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 512', 'TRANSMISSION MEDIA AND ANTENNA SYSTEMS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 512L', 'TRANSMISSION MEDIA AND ANTENNA SYSTEMS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 513', 'DATA COMMUNICATIONS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 513L', 'DATA COMMUNICATIONS (LAB)', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-PS1', 'THESIS I', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('SCL 3', 'THE SOCIAL TEACHING OF THE CHURCH', 3 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 512', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('COMP 511', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('GE 302', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 511', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 511L', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 512', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 512L', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 513', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 513L', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-PS1', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('SCL 3', 'First Semester', 'Fifth Year', 'ElectronicsEngineering')

-------------------------------------------------------------------

--Fifth Year Second Sem
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('GE 303', 'SAFETY MANAGEMENT', 1 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 521', 'COMMUNICATION SYSTEMS ANALYSIS AND DESIGN', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 522', 'ECE LAWS, CONTRACTS AND ETHICS', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE 523', 'SEMINARS AND FIELD TRIPS', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-PS2', 'THESIS II', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-PRACT', 'PRACTICUM', 0 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-ELEC2', 'ECE ELECTIVE II', 2 , 1)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-ELEC3', 'ECE ELECTIVE III', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('ECE-ELEC4', 'ECE ELECTIVE IV', 3 , 0)
Insert into Course (Course_ID, Course_Name,   Lec_Units , Lab_Units)
Values ('SCL 9', 'MARRIAGE AND FAMILY', 3 , 0)

-------------------------------------------------------------------

Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('GE 303', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 521', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 522', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE 523', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-PS2', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-PRACT', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-ELEC2', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-ELEC3', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('ECE-ELEC4', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')
Insert Into CurriculumTable(Course_ID, Semester, Year, Program)
Values('SCL 9', 'Second Semester', 'Fifth Year', 'ElectronicsEngineering')